@startuml zcl_ioc_container

hide empty members

class ZCL_IOC_CONTAINER {
	- MAPPING_TABLE[]
	- INSTANCE_MAPPING_TABLE[]
	+ REGISTER()
	+ DEREGISTER()
	+ REGISTER_INSTANCE()
	+ DEREGISTER_INSTANCE()
	+ RESOLVE()
	- ASSERT_OBJ_CREATE_IS_POSSIBLE()
	- CHECK_CREATE_PRIVATE()
	- CHECK_NOT_INSTANTIATABLE()
	- CHECK_NON_PUBLIC_CONSTRUCTOR()
	- GET_PARAMETER_TYPE_NAME()
}

class ZCX_IOC_CONTAINER {
	{static} - OBJECT_IS_NOT_INSTANTIATABLE
	{static} - CONSTRUCTOR_IS_PRIVATE
	{static} - CLASS_IS_CREATE_PRIVATE
	{static} - ERROR_IN_TYPE_DETERMINATION
}

ZCL_IOC_CONTAINER .right.> ZCX_IOC_CONTAINER: <<throws>>

@enduml

@startuml test_classes

hide empty members

interface ZIF_IOC_A <<interface>>
interface ZIF_IOC_B <<interface>>

class ZCL_IOC_A {
	+ IOC_B: ZIF_IOC_B
	+ CONSTRUCTOR(IOC_B: ZIF_IOC_B)
}

abstract class ZCL_IOC_ABSTRACT

class ZCL_IOC_CREATE_PRIVATE <<Create Private>> {
	+ CONSTRUCTOR()
}
class ZCL_IOC_PRIVATE_CONSTRUCTOR {
	- CONSTRUCTOR()
}

class ZCL_IOC_B_SUPER

class ZCL_IOC_B_SUBCL {
	+ IOC_C: ZCL_IOC_C
	+ CONSTRUCTOR(IOC_C: ZCL_IOC_C)
}

class ZCL_IOC_C {
	+ STRING: NAME
	+ INT4: AGE
	+ CONSTRUCTOR(STRING: NAME, INT4: AGE?)
}

ZIF_IOC_A <|.. ZCL_IOC_A
ZIF_IOC_A <|.. ZCL_IOC_ABSTRACT
ZIF_IOC_A <|.right. ZCL_IOC_CREATE_PRIVATE
ZIF_IOC_A <|.left. ZCL_IOC_PRIVATE_CONSTRUCTOR
ZCL_IOC_A o-right- ZIF_IOC_B
ZIF_IOC_B <|.. ZCL_IOC_B_SUPER
ZCL_IOC_B_SUPER <|-- ZCL_IOC_B_SUBCL
ZCL_IOC_B_SUBCL o-right- ZCL_IOC_C

@enduml